### ISSUE TITLE
SSH.NET Dependency Issue

### ISSUE THREAD

**Issue by MRhyne1931** [JohnTheGr8/Renci.SshNet.Async#1]
The dependency of SSH.net being used is 2016.1.0.  There is a known issue around disposing when trying to disconnect.  Should this code base downgrade the SSH.NET dependency to 2016.0.0?  Here is the issue - https://github.com/sshnet/SSH.NET/issues/355

**Comment by JohnTheGr8** [comment]
Hi. You could use [Renci.SshNet.Async 1.2.0](https://www.nuget.org/packages/Renci.SshNet.Async/1.2.0) which requires `SSH.NET >= 2016.0.0`
