### ISSUE TITLE
Add ConnectAsync method

### ISSUE THREAD

**Issue by Spyromaniac31** [JohnTheGr8/Renci.SshNet.Async#10]
If possible, I think a ConnectAsync() method would be very useful. Currently, when a client is trying and failing to connect to a server, the Connect() method lasts several seconds and thus freezes the app that it is in. Adding an asynchronous connection method would allow apps to establish SSH or SFTP connections without holding up the UI thread.

**Comment by JohnTheGr8** [comment]
SSH.NET does not allow for this, unfortunately. See #5

**Comment by Spyromaniac31** [comment]
Alright, thanks for the info. I was able to use Task.Run() to connect using a different thread, which solved the issues I was having.

**Comment by JohnTheGr8** [comment]
FYI there is an ongoing effort to add task-based async methods to SSH.NET directly, including a `ConnectAsync` method, which you can follow at sshnet/SSH.NET#819 ... I don't think there's an ETA for when it will be ready, however.
