### ISSUE TITLE
Delete Async Method?

### ISSUE THREAD

**Issue by james-lappin-cko** [JohnTheGr8/Renci.SshNet.Async#4]
Hey

Firstly, thank for creating the library, really easy to use.

Wondering if I'm missing something, is there a way to do DeleteAsync?

Thanks

**Comment by JohnTheGr8** [comment]
Hey. I forgot to respond to this one, sorry about that.

SSH.NET does not expose a `Begin`/`End` method for all operations, therefore I cannot write an async extension method for everything. `Delete`, `DeleteFile` and `DeleteDirectory` are among them.

If you need this, consider opening an issue about it in [sshnet/SSH.NET](https://github.com/sshnet/SSH.NET)
