### ISSUE TITLE
Support for cancellationToken

### ISSUE THREAD

**Issue by marcinzi** [JohnTheGr8/Renci.SshNet.Async#6]
The async methods do not expose CancellationToken parameter.
Since the underlying methods do have access to AsyncCallback, perhaps it would be possible to cancel the upload/download operation in progress?

**Comment by JohnTheGr8** [comment]
Hi. I am not sure what you mean regarding AsyncCallback... but the APM model does not support cancellation, so there is no good way of achieving this as far as I know. Here's a [related StackOverflow question](https://stackoverflow.com/questions/24980427/task-factory-fromasync-with-cancellationtokensource).
